services:
  api:
    build: ./apps/api
    ports:
      - "3000:3000"
    container_name: meu-api

  web:
    build: ./apps/web
    ports:
      - "8080:80"
    container_name: meu-web
    depends_on:
      - api
